repos:
-   repo: https://github.com/ambv/black
    rev: stable
    hooks:
    - id: black
      language_version: python3.7
-   repo: local
    hooks:
    -   id: tests
        name: run tests
        entry: ve/bin/python3.7 -m pytest -v -p no:warnings
        language: python
        types: [python]
