language: python
python:
  - "3.6"
# command to install dependencies
install:
  - pip install -r requirements.txt
# command to run tests
script: python -m pytest tests/ --cov=app --cov-report term 
branches:
  only:
    - master

# Push the results back to codecov
after_success:
- codecov